### ISSUE TITLE
Unable to save.  Error:`callback is not a function`

### ISSUE THREAD

**Issue by tkodev** [saltfactory/front-matter-editor#1]
**Code:**
```js
var editor = require('front-matter-editor');
var mdPath = "/Users/sysuser/Google Drive/projects/public/code/htko/site-base/scripts/README.md";
editor.read(mdPath).data(function(data,matter){
  data.photo.unshift( data.cover );
  delete data.cover;
  matter.data = data;
}).save(mdPath, {prefix:"test-"});
```

**Error:**
```
/Users/sysuser/Google Drive/projects/public/code/htko/site-base/scripts/node_modules/front-matter-editor/index.js:65
      callback(err, data);
      ^

TypeError: callback is not a function
    at fs.writeFile (/Users/sysuser/Google Drive/projects/public/code/htko/site-base/scripts/node_modules/front-matter-editor/index.js:65:7)
    at fs.js:1305:7
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by gbirke** [comment]
This happens because the saving of the changed frontmatter fails and the example code does not provide an error handler. Try the following last line:

```javascript
}).save(mdPath, {prefix:"test-"}, function(err, data) {
    if (err) {
        console.log( 'Could not write to ' + mdPath, err );
    }
});
```
The error should then be logged and you can find out what it was.
